import type { Incident, Storyline } from "../storyteller";

// Lucknow's cases: the city of tehzeeb, kababs, ghazals and kite strings, where everyone knows everyone's business
// and nobody says the important thing out loud.

const ZOYA = "lko_009", KABIR = "lko_010", ARJUN = "lko_021", SANA = "lko_022", ANUJ = "lko_026", TARA = "lko_027", ANANYA = "lko_028",
  ROHAN = "lko_029", RAMESH = "lko_030", SHYAM = "lko_032", NASREEN = "lko_033", IMRAN = "lko_034",
  ALOK = "lko_036", FARAH = "lko_037", VIKRAM = "lko_038", POOJA = "lko_039", RAJENDRA = "lko_040", KAMLA = "lko_041",
  ADITYA = "lko_042", NIDHI = "lko_043", FAIZAN = "lko_044", YUSUF = "lko_045", REKHA = "lko_046", ISHITA = "lko_047";

export const LUCKNOW_STORYLINES: Storyline[] = [
  {
    id: "kabir_ghazal", title: "The ghazal about someone", icon: "🎶",
    goal: "Get Kabir and Zoya on a date.",
    brief: "Kabir has written a ghazal about Zoya and has never told her. Shy Tara has a sketchbook full of drawings of Kabir.",
    well: "Kabir told Zoya the truth, and she said yes.",
    badly: "Kabir laid his heart on the line, and Zoya turned him down.",
    seeds: [
      { who: KABIR, memory: "I wrote a ghazal called 'Chowk ki Shaam' about Zoya Ansari. I've never told her, or anyone. I'm singing it at Saturday's mehfil in the back room of the kabab house.", feels: { toward: ZOYA, affection: 45 } },
      { who: TARA, memory: "I have a crush on Kabir Qureshi from Nawab Kabab House. Half my sketchbook is drawings of him with his guitar. Nobody knows.", feels: { toward: KABIR, affection: 40 } },
    ],
    beats: [
      { actor: KABIR, target: ZOYA, headline: "🎶 Kabir is working up the nerve to invite Zoya to Saturday's mehfil", reason: "I want to invite Zoya to the mehfil on Saturday without giving away that the new ghazal is about her.",
        topic: "Saturday's mehfil at the kabab house", stakes: "Kabir is nervous and joking too much; he badly wants Zoya to come and hear him sing on Saturday." },
      { actor: TARA, target: KABIR, headline: "✏️ Shy Tara is about to show Kabir a drawing she made of him", reason: "I want to give Kabir the sketch I made of him playing, before I lose my nerve.",
        topic: "a drawing Tara made", stakes: "Tara is painfully shy about her art; handing Kabir a drawing of himself is a huge step for her." },
      { actor: ZOYA, target: KABIR, headline: "👀 Zoya has heard Kabir's new ghazal is about 'a girl from the institute' and wants answers",
        prelude: [{ who: ZOYA, memory: "Ishita told me Kabir's new ghazal is about a girl who works at the research institute. I'm the only girl from our lane who works there." }],
        reason: "Someone told me Kabir's new ghazal is about a girl from the institute. I want to know if it's me, without looking foolish.", topic: "who Kabir's ghazal is about",
        stakes: "Zoya is direct and impatient; Kabir hides behind couplets when he's cornered." },
      { actor: KABIR, target: ZOYA, headline: "💘 Kabir is going to tell Zoya the truth about the ghazal", reason: "No more jokes and no more couplets. I'm going to tell Zoya the ghazal is about her, and ask her out.",
        topic: "the ghazal, and how Kabir feels", stakes: "Kabir is laying his feelings on the line. Zoya can say yes, no, or that she needs time.", proposal: "date" },
    ],
  },
  {
    id: "library_godaan", title: "A book he's already read", icon: "📚",
    goal: "Get Inspector Singh and Farah to the Mahotsav together.",
    brief: "Vikram, a widower, keeps borrowing the same Premchand novel just to speak to Farah the librarian. His daughter Ananya has noticed.",
    well: "Farah and Vikram are going to the Lucknow Mahotsav together.",
    badly: "Farah and Vikram couldn't find the courage. The Mahotsav will come and go.",
    seeds: [
      { who: VIKRAM, memory: "I've borrowed 'Godaan' three times this month just to speak to Farah ji at the library counter. Part of me feels I'm betraying Amrita.", feels: { toward: FARAH, affection: 40 } },
      { who: FARAH, memory: "Inspector Vikram Singh keeps borrowing a book he has already read. I think it might be because of me, and I don't know what to do with that.", feels: { toward: VIKRAM, affection: 35 } },
      { who: ANANYA, memory: "Papa has been going to the library almost every day. He hums old film songs now. Something is going on and he won't say." },
    ],
    beats: [
      { actor: VIKRAM, target: FARAH, headline: "📚 Inspector Singh is at the library again, with a book he's already read", reason: "I'm returning the same book again. Today I'll try to ask Farah ji to the Lucknow Mahotsav.",
        topic: "the book, and the Lucknow Mahotsav", stakes: "Vikram is a widower who hasn't asked anyone anywhere in twenty years; Farah is shy and lonely, and both are careful of what the lane will say." },
      { actor: ANANYA, target: VIKRAM, headline: "🕵️ Ananya has worked out why her father keeps going to the library", reason: "I've worked out Papa goes to the library for Farah aunty. I need to know if he's moving on from Mummy, and whether I'm all right with that.",
        topic: "Papa and the librarian", stakes: "Ananya lost her mother three years ago. She's direct, but this is raw for both of them." },
      { actor: SANA, target: FARAH, headline: "🤐 Sana overheard gossip about her aunt and the inspector",
        prelude: [{ who: SANA, memory: "At Sharmaji's, Kamla aunty was telling everyone that Inspector sahib is sweet on my Phuphi. I hate gossip, but I hate seeing her lonely more." }],
        reason: "Kamla aunty is gossiping about Phuphi and Inspector sahib. I want her to hear it from me, kindly, and to tell her she deserves to be happy.", topic: "the gossip about Farah and Vikram",
        stakes: "Sana is private and principled; Farah dreads being talked about." },
      { actor: FARAH, target: VIKRAM, headline: "💌 Farah has an answer for Inspector Singh", reason: "I'm going to stop hiding behind the issue desk and ask Vikram ji to go to the Mahotsav with me.",
        topic: "the Mahotsav, together", stakes: "Two shy, lonely adults trying to be brave.", proposal: "date" },
    ],
  },
  {
    id: "aditya_shayari", title: "Adi Lakhnavi", icon: "🪶",
    goal: "Get Aditya to tell his father about the poetry, without breaking them apart.",
    brief: "Aditya is reciting at Sunday's mushaira under a pen name. His father Rajendra, the station superintendent, thinks he is revising for the railway exam.",
    well: "Rajendra knows about the poetry, and father and son are still talking.",
    badly: "The truth came out, and it drove Aditya and his father apart.",
    seeds: [
      { who: ADITYA, memory: "I've put my name down for Sunday's mushaira as 'Adi Lakhnavi'. Papa thinks I'm revising for the railway recruitment exam. If he finds out, he'll explode." },
      { who: RAJENDRA, memory: "Aditya's railway recruitment exam is in two weeks. A permanent post, a pension, a quarter. I've worked twenty years so he could have that." },
      { who: KAMLA, memory: "I found a notebook of poetry under Aditya's mattress. It's actually good. Should I tell Rajendra? Aditya would never forgive me." },
    ],
    beats: [
      { actor: KAMLA, target: ADITYA, headline: "📒 Kamla found a notebook hidden under Aditya's mattress", reason: "I found Aditya's notebook of poetry. I want him to tell me the truth himself before his father finds out.",
        topic: "the notebook", stakes: "Kamla is nosy but loving; Aditya is secretive and terrified of his father finding out." },
      { actor: ADITYA, target: YUSUF, headline: "🪶 Aditya secretly asks old Mirza sahib to hear his verses", reason: "Mirza sahib knows real Urdu poetry. I want his honest opinion on my nazm before Sunday, and I need him to keep it to himself.",
        topic: "Aditya's nazm for the mushaira", stakes: "Aditya has never read his verses to anyone; Yusuf is courtly but will not flatter bad poetry." },
      { actor: RAJENDRA, target: ADITYA, headline: "🚉 The superintendent knows Aditya skipped exam coaching again",
        prelude: [{ who: RAJENDRA, memory: "Aditya skipped the exam coaching class again. The instructor rang me at the station. Something is going on and I will get to the bottom of it." }],
        reason: "Aditya skipped coaching again. I want an explanation, now.", topic: "the railway exam",
        stakes: "Rajendra is dutiful and proud; Aditya is torn between his father and his verses. It can get heated." },
      { actor: ADITYA, target: RAJENDRA, headline: "🎤 Aditya is going to tell his father about the mushaira", reason: "I'm going to show Papa my notebook and tell him I don't want the railway job.",
        topic: "Aditya's poetry and his future", stakes: "This could break them or bring them closer." },
    ],
  },
  {
    id: "kabab_sale", title: "The Delhi offer", icon: "🍢",
    goal: "Get Imran to come clean about selling the kabab house, and keep his friends.",
    brief: "A restaurant chain from Delhi has offered to buy Nawab Kabab House, eighty years in the family. Imran has told nobody, least of all Kabir, who sings there.",
    well: "Imran told the truth about the offer, and nobody walked away.",
    badly: "The secret came out badly, and it cost Imran a friend.",
    seeds: [
      { who: IMRAN, memory: "Men from a Delhi restaurant chain measured up Nawab Kabab House yesterday. If I sell, Kabir never has to stand over a coal sigri again. I haven't told him; the back room is where he sings." },
      { who: KAMLA, memory: "I saw two men in suits with a measuring tape at Nawab Kabab House this morning. Imran bhai wouldn't sell... would he?" },
    ],
    beats: [
      { actor: KAMLA, target: KABIR, headline: "🏷️ Kamla saw men with a measuring tape at the kabab house", reason: "I saw men in suits measuring up the kabab house. Kabir deserves to know, even if it's not my business.",
        topic: "the men at the kabab house", stakes: "Kamla loves news; Kabir knows nothing about it." },
      { actor: KABIR, target: IMRAN, headline: "🍢 Kabir confronts his father: is the kabab house for sale?", reason: "Kamla aunty says men from Delhi measured up the shop. I need Abbu to tell me the truth. That's Dada's shop, and it's where I sing.",
        topic: "selling the kabab house", stakes: "Imran is loud and proud and kept this from his son; Kabir feels betrayed. It can get heated." },
      { actor: IMRAN, target: RAMESH, headline: "🥭 Imran owes Ramesh the truth about the shop", reason: "If I sell, Ramesh loses his best customer for the orchard's raw mangoes and mango wood. I owe him the truth.",
        topic: "the sale and the orchard's orders", stakes: "Ramesh keeps his money worries to himself; Imran hates letting people down." },
    ],
  },
  {
    id: "dadaji_heart", title: "Dadaji's appointment slip", icon: "🫀",
    goal: "Get Shyam Lal to let his family help.",
    brief: "Dadaji Shyam Lal is hiding heart tests from his family. His grandson Anuj has found the appointment slip.",
    well: "Shyam Lal let his family in. He will not face the tests alone.",
    badly: "Shyam Lal shut his family out. He is facing the tests alone.",
    seeds: [
      { who: SHYAM, memory: "Dr. Ansari wants me back at KGMU for heart tests next Tuesday. I've told nobody. I won't be the old man everyone tiptoes around." },
      { who: ANUJ, memory: "I found Dadaji's hospital slip in his coat pocket. Cardiology, KGMU, next Tuesday. He hasn't said a word to any of us." },
      { who: NASREEN, memory: "Shyam Lal Mishra's heart results worry me. He asked me not to tell his family; I have to respect that, but I want him to tell them." },
    ],
    beats: [
      { actor: ANUJ, target: SHYAM, headline: "🫀 Anuj found a cardiology slip in Dadaji's coat", reason: "I found Dadaji's heart appointment slip. I want him to tell me what's going on.",
        topic: "Dadaji's appointment", stakes: "Shyam Lal is proud and hates being treated as fragile; Anuj is careful and loves him." },
      { actor: NASREEN, target: SHYAM, headline: "🩺 Dr. Ansari wants Shyam Lal to tell his family", reason: "Shyam Lal ji's results worry me. I want to persuade him to tell his family before Tuesday.",
        topic: "telling his family about the tests", stakes: "Doctor and patient; she can't break his confidence, and he's stubborn." },
      { actor: ANUJ, target: RAMESH, headline: "😟 Anuj can't keep Dadaji's secret any longer", reason: "Dadaji made me promise not to tell, but Papa needs to know about the heart tests.",
        topic: "Dadaji's heart tests", stakes: "Anuj is breaking a promise; Ramesh keeps his worries to himself." },
      { actor: RAMESH, target: SHYAM, headline: "🥭 Ramesh confronts his father about the heart tests", reason: "Babuji hid his heart tests from us. I'm angry and frightened, and I'm not leaving until he lets us help.",
        topic: "the heart tests", stakes: "Two stubborn orchard men who love each other; both are proud and hurt." },
    ],
  },
  {
    id: "pooja_bengaluru", title: "The Bengaluru offer", icon: "🏏",
    goal: "Help Pooja decide about Bengaluru without leaving anyone behind.",
    brief: "Pooja has been offered head coach at a studio in Bengaluru. She has not told her sister Tara, or Arjun, whose cricket trials are three weeks away.",
    well: "Pooja made her choice, and the people who count on her are still on her side.",
    badly: "Pooja made her choice, and someone who counted on her feels abandoned.",
    seeds: [
      { who: POOJA, memory: "A studio in Bengaluru has offered me head coach, starting next month. It's the job I've wanted for years. I haven't told Tara, or Arjun, who's counting on me for his trials." },
      { who: ARJUN, memory: "Pooja didi is training me for the Uttar Pradesh under-23 trials in three weeks. She's the only coach who's ever believed in me.", feels: { toward: POOJA, admiration: 45 } },
    ],
    beats: [
      { actor: TARA, target: POOJA, headline: "🧳 Tara found a Bengaluru flat listing open on her sister's phone",
        prelude: [{ who: TARA, memory: "I saw a rental listing for a flat in Bengaluru open on Pooja didi's phone. She hasn't said anything. Is she leaving me here?" }],
        reason: "Didi is planning to move to Bengaluru without telling me. I want the truth.", topic: "the Bengaluru flat listing",
        stakes: "Sisters: Pooja hates being treated as Tara's parent; Tara hates being left out of decisions." },
      { actor: ARJUN, target: POOJA, headline: "🏏 Arjun hears his coach might leave before his trials",
        prelude: [{ who: ARJUN, memory: "Tara let it slip that Pooja didi might move to Bengaluru next month, before my trials." }],
        reason: "Pooja didi might leave before my trials and she didn't tell me. I feel left behind again.", topic: "Pooja leaving for Bengaluru",
        stakes: "Arjun is loyal and insecure about being left behind; Pooja is impulsive and driven." },
      { actor: POOJA, target: ARJUN, headline: "🏋️ Pooja has made her decision about Bengaluru", reason: "I've decided about Bengaluru. Arjun deserves to hear it from me first, with a plan for his trials either way.",
        topic: "Pooja's decision", stakes: "Pooja is choosing between her dream and the people counting on her." },
    ],
  },
  {
    id: "stolen_slides", title: "Whose idea was it?", icon: "💼",
    goal: "Get Nidhi to make it right with Ananya.",
    brief: "Nidhi presented Ananya's work as the team's idea, days before a promotion decision. Faizan, meanwhile, is trying to ask Nidhi to lunch.",
    well: "Nidhi owned up, and Ananya can work with her again.",
    badly: "Nidhi and Ananya are finished as colleagues who trust each other.",
    seeds: [
      { who: ANANYA, memory: "In Monday's meeting Nidhi Kapoor presented my user-retention model as 'our team's idea'. My name wasn't on a single slide.", feels: { toward: NIDHI, resentment: 40 } },
      { who: NIDHI, memory: "I used Ananya Singh's model in my pitch without crediting her. I panicked; the promotion decision is Friday. I feel sick about it." },
      { who: FAIZAN, memory: "I've kept Nidhi's favourite table at the arcade coffee house free five days in a row. Today I'll actually say something to her.", feels: { toward: NIDHI, affection: 40 } },
    ],
    beats: [
      { actor: ANANYA, target: NIDHI, headline: "💼 Ananya is about to confront Nidhi about stolen credit", reason: "Nidhi presented my model as hers. I'm going to say it to her face, calmly but clearly.",
        topic: "who built the retention model", stakes: "Ananya is direct and fair-minded and hates stolen credit; Nidhi is ambitious and exhausted. Neither makes nice too fast." },
      { actor: FAIZAN, target: NIDHI, headline: "☕ Faizan kept Nidhi's table again; today he'll say something", reason: "I'm finally going to ask Nidhi to lunch, properly.",
        topic: "lunch, finally", stakes: "Nidhi is having an awful week; Faizan is easygoing and nervous." },
      { actor: NIDHI, target: ANANYA, headline: "🙏 Nidhi has to decide whether to own up before Friday", reason: "Before Friday's promotion decision, I have to tell Ananya the truth and decide whether to credit her in front of everyone.",
        topic: "the pitch and the promotion", stakes: "Nidhi's promotion is on the line." },
    ],
  },
  {
    id: "rohan_promise", title: "The third broken promise", icon: "🥘",
    goal: "Mend things between Rohan and his father.",
    brief: "Dr. Tiwari has broken three promises to his son Rohan this year. Rohan has stopped pretending it is fine.",
    well: "Rohan is giving his father one more chance, and this time Dr. Tiwari means it.",
    badly: "Rohan has heard it all before. He does not believe his father any more.",
    seeds: [
      { who: ROHAN, memory: "Papa promised to come to my first chaat tasting on Saturday. He didn't show. Third broken promise this year.", feels: { toward: ALOK, resentment: 35 } },
      { who: ALOK, memory: "I missed Rohan's tasting; the experiment overran. I keep telling myself he understands." },
    ],
    beats: [
      { actor: ROHAN, target: ALOK, headline: "🥘 Rohan is done pretending his father's broken promises don't hurt", reason: "Papa missed my tasting. I'm done pretending it's fine; he needs to hear it.",
        topic: "the missed tasting", stakes: "Rohan is warm but guarded; Alok is kind and absent-minded." },
      { actor: ALOK, target: ZOYA, headline: "🔬 Dr. Tiwari asks Zoya to cover for him so he can make it up to Rohan", reason: "I need Zoya to run Saturday's assay so I can finally be there for Rohan.",
        topic: "covering Saturday's assay", stakes: "Zoya wants to impress Dr. Tiwari, but it's her Saturday too, and the mehfil is that evening." },
      { actor: ALOK, target: ROHAN, headline: "🍲 Dr. Tiwari is trying to make it right with his son", reason: "I've cleared my Saturday. I want to tell Rohan I'll be at the next tasting, and mean it this time.",
        topic: "the next tasting", stakes: "Rohan may not believe him yet." },
    ],
  },
  {
    id: "ishita_audition", title: "Raag Yaman", icon: "🎼",
    goal: "Get Ishita onto a stage before her audition.",
    brief: "Ishita has an audition at the Bhatkhande music college and has told no one, not even her mother.",
    well: "Ishita has people behind her, and a stage to sing on before the audition.",
    badly: "Ishita is facing the audition feeling more alone than before.",
    seeds: [
      { who: ISHITA, memory: "I've got an audition at the Bhatkhande music college on the 20th. I'd have to drop my evening shifts at the shop to practise. I haven't told Mummy or Kamla aunty." },
    ],
    beats: [
      { actor: ISHITA, target: KAMLA, headline: "🎼 Ishita has to ask her boss for time off", reason: "I have to ask Kamla aunty to let me drop my evening shifts for the audition, and she's already short-handed.",
        topic: "Ishita's shifts", stakes: "Ishita is shy and hates being put on the spot; Kamla depends on her and will want to know everything." },
      { actor: REKHA, target: ISHITA, headline: "✉️ Rekha found the music college letter in Ishita's bag",
        prelude: [{ who: REKHA, memory: "I found a letter from the Bhatkhande music college in Ishita's bag: an audition on the 20th. Why didn't she tell me?" }],
        reason: "Ishita has an audition at the music college and didn't tell me. I want to know why she hid it.", topic: "the audition letter",
        stakes: "Mother and daughter; Rekha works late and worries Ishita doesn't believe in herself." },
      { actor: KABIR, target: ISHITA, headline: "🎙️ Kabir wants Ishita to sing at Saturday's mehfil", reason: "I heard Ishita sings beautifully. I want her to sing with me on Saturday: a stage before her audition.",
        topic: "singing together on Saturday", stakes: "Ishita is shy; Kabir is playful and persuasive." },
    ],
  },
];

export const LUCKNOW_CASE_ORDER = ["aditya_shayari", "kabir_ghazal", "dadaji_heart", "library_godaan", "stolen_slides", "rohan_promise", "kabab_sale", "pooja_bengaluru", "ishita_audition"];

export const LUCKNOW_INCIDENTS: Incident[] = [
  { id: "mahotsav", headline: "🎪 The Lucknow Mahotsav opens on Saturday evening by the Gomti", who: "everyone",
    memory: "The Lucknow Mahotsav opens on Saturday evening: craft stalls, kabab counters, a mushaira and fireworks over the Gomti. Everyone's talking about who they'll go with." },
  { id: "mehfil", headline: "🎤 Nawab Kabab House puts up a notice for Saturday's mehfil", who: [KABIR, ISHITA, TARA, ZOYA, ADITYA, IMRAN],
    memory: "Nawab Kabab House has a notice up for a mehfil in the back room on Saturday night, with Kabir's name at the top." },
  { id: "power_cut", headline: "⚡ A power cut blacks out the Charbagh side for an hour", who: [ANUJ, RAJENDRA, ADITYA, KAMLA, FAIZAN, NIDHI],
    memory: "The power went out around Charbagh for an hour today. The metro stopped, the shop fridges went warm, and the substation crew were run off their feet." },
  { id: "lost_parrot", headline: "🦜 'LOST: Mithu' notices appear all over Hazratganj", who: [YUSUF, TARA, ROHAN, FARAH, SHYAM],
    memory: "Notices for a lost parrot called Mithu are up all over Hazratganj. Old Mirza sahib is looking for her; she was his late wife's parrot." },
  { id: "orchard_plan", headline: "📰 The paper says the mango orchard may be sold for flats", who: [RAMESH, SHYAM, ROHAN, IMRAN, KAMLA],
    memory: "The morning paper says the Dussehri Mango Orchard is being looked at by a builder for a block of flats." },
  { id: "wedding_rumour", headline: "💍 Rumour at Sharmaji's: someone in the lane is getting engaged", who: [KAMLA, NIDHI, POOJA, NASREEN, REKHA],
    memory: "Kamla swears someone in the lane is about to get engaged. She won't say who, which means she doesn't know." },
  { id: "kites", headline: "🪁 The sky over Chowk fills with kites for the evening pench", who: [YUSUF, ANUJ, SHYAM, ARJUN, KABIR],
    memory: "The rooftops of Chowk were full of kite flyers this evening, shouting 'woh kaata!' every time a string was cut." },
];
